//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitapOgr.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Islemler
    {
        public int IslemID { get; set; }
        public Nullable<int> OgrenciID { get; set; }
        public Nullable<int> KitapID { get; set; }
        public Nullable<System.DateTime> AlinanTarih { get; set; }
        public Nullable<System.DateTime> VerilenTarih { get; set; }
    
        public virtual Kitaplar Kitaplar { get; set; }
        public virtual Ogrenciler Ogrenciler { get; set; }
    }
}
