//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitapOgr.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitaplar()
        {
            this.Islemlers = new HashSet<Islemler>();
        }
    
        public int KitapID { get; set; }
        public Nullable<int> ISBN_No { get; set; }
        public string KitabAdi { get; set; }
        public Nullable<int> YazarID { get; set; }
        public Nullable<int> TurID { get; set; }
        public Nullable<int> SayfaSayisi { get; set; }
        public Nullable<int> Puan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Islemler> Islemlers { get; set; }
        public virtual Turler Turler { get; set; }
        public virtual Yazarlar Yazarlar { get; set; }
    }
}
